### ISSUE TITLE
Grid GridTRElement::select not firing Vaadin selection change listener

### ISSUE THREAD

**Issue by drewoko** [vaadin/testbench#1132]
TestBench from Vaadin BOM 12.0.5

Grid with selection value change listener. 

` grid.asSingleSelect().addValueChangeListener(event -> EVENT);`

Using TestBench test selecting that row and executing select() method. As result on UI I see that row is highlighted, but value change listener was not triggered. 

Demo app from Vaadin starter for demonstrating issue. 
[demo-app-vaadin.zip](https://github.com/vaadin/testbench/files/2850196/demo-app-vaadin.zip)

**Comment by alvarezguille** [comment]
Fix has been released in vaadin-components-testbench 2.0.1 and will be included in next maintenance release of 12.0.x and 13.0.x

**Comment by KasparScherrer** [comment]
Hello, can you fix this for multi select grids too? I have exactly the same issue as drewoko, but my grid is multi select. Using Vaadin 13.0.3

**Comment by tboehm-xdev** [comment]
Multi-Select is still not working.
Here is an minimal example to reproduce it.
[TestBenchGridSelectionBug.zip](https://github.com/vaadin/testbench/files/5135030/TestBenchGridSelectionBug.zip)
Deploy it to your fav application server, change 'TestMainLayout' URL/Port if needed.

Tested with Vaadin 14.1.19 and 14.3.3.
